const items = [
  {
    id: 1,
    name: "Mètre",
    utility: "baignoire",
    image: "https://i.imgur.com/cUzX22l.jpg",
    desc: "Mesure mètre à ruban Stanley Tylon bi-matière 5 mètres x 19 mm classe 2",
    price: 6.5,
  },
  {
    id: 2,
    name: "Niveau à bulle",
    utility: "baignoire",
    image: "https://i.imgur.com/HtYneyC.png",
    desc: "Longueur : 400 mm",
    price: 20,
  },
  {
    id: 3,
    name: "Règle de maçon",
    utility: "baignoire",
    image: "https://i.imgur.com/W7dT9zB.jpg",
    desc: "2 voiles (3 alvéoles). Section 100 x 18 mm. Epaisseur 1 mm +/- 0,05. Longueur : 6m.",
    price: 30.5,
  },
  {
    id: 4,
    name: "Clef à molette",
    utility: "baignoire",
    image: "https://i.imgur.com/QfLWbqM.jpg",
    desc: "Clé à molette 30 pouces Clé à molette, clé à fourche large, forgée, chromée, outils à main, 775 MM",
    price: 328,
  },
  {
    id: 5,
    name: "Clef plate",
    utility: "baignoire",
    image: "https://i.imgur.com/gJjGbzH.jpg",
    desc: "Clé plate Facom 20 X 22 mm",
    price: 9.05,
  },
  {
    id: 6,
    name: "Silicone",
    utility: "baignoire",
    image: "https://imgur.com/a/BW2ERG9",
    desc: "Mastic sanitaire silicone acétique surface émaillée SA blanc-300ml",
    price: 5.44,
  },
  {
    id: 7,
    name: "Pistolet à silicone",
    utility: "baignoire-évier",
    image: "",
    desc: "Pistolet à silicone - 450 ml",
    price: 11.26,
  },
  {
    id: 8,
    name: "Robinet baignoire",
    utility: "baignoire",
    image: "",
    desc: "Robinet mitigeur de baignoire et douche chromé fixation murale",
    price: 34.9,
  },
  {
    id: 9,
    name: "",
    utility: "baignoire",
    image: "",
    desc: "",
    price: 0.0,
  },
  {
    id: 10,
    name: "",
    utility: "baignoire",
    image: "",
    desc: "",
    price: 0.0,
  },
  {
    id: 11,
    name: "",
    utility: "baignoire",
    image: "",
    desc: "",
    price: 0.0,
  },
  {
    id: 12,
    name: "",
    utility: "baignoire",
    image: "",
    desc: "",
    price: 0.0,
  },
  {
    id: 13,
    name: "",
    utility: "baignoire",
    image: "",
    desc: "",
    price: 0.0,
  },
  {
    id: 14,
    name: "",
    utility: "baignoire",
    image: "",
    desc: "",
    price: 0.0,
  },
  {
    id: 15,
    name: "",
    utility: "baignoire",
    image: "",
    desc: "",
    price: 0.0,
  },
];
