const items = [
  {
    id: 1,
    name: "Mètre",
    utility: "baignoire",
    image: "https://i.imgur.com/cUzX22l.jpg",
    desc: "Mesure mètre à ruban Stanley Tylon bi-matière 5 mètres x 19 mm classe 2",
    price: 6.5,
  },
  {
    id: 2,
    name: "Niveau à bulle",
    utility: "baignoire",
    image: "https://i.imgur.com/HtYneyC.png",
    desc: "Longueur : 400 mm",
    price: 20,
  },
  {
    id: 3,
    name: "Règle de maçon",
    utility: "baignoire-carrelage",
    image: "https://i.imgur.com/W7dT9zB.jpg",
    desc: "2 voiles (3 alvéoles). Section 100 x 18 mm. Epaisseur 1 mm +/- 0,05. Longueur : 6m.",
    price: 30.5,
  },
  {
    id: 4,
    name: "Clef à molette",
    utility: "baignoire",
    image: "https://i.imgur.com/QfLWbqM.jpg",
    desc: "Clé à molette 30 pouces Clé à molette, clé à fourche large, forgée, chromée, outils à main, 775 MM",
    price: 328,
  },
  {
    id: 5,
    name: "Clef plate",
    utility: "baignoire",
    image: "https://i.imgur.com/gJjGbzH.jpg",
    desc: "Clé plate Facom 20 X 22 mm",
    price: 9.05,
  },
  {
    id: 6,
    name: "Silicone",
    utility: "baignoire",
    image: "https://i.imgur.com/1lUb0hf.jpg",
    desc: "Mastic sanitaire silicone acétique surface émaillée SA blanc-300ml",
    price: 5.44,
  },
  {
    id: 7,
    name: "Pistolet à silicone",
    utility: "baignoire-évier",
    image: "https://i.imgur.com/tUiD8je.jpg",
    desc: "Pistolet à silicone - 450 ml",
    price: 11.26,
  },
  {
    id: 8,
    name: "Robinet baignoire",
    utility: "baignoire",
    image: "https://i.imgur.com/0ALSrXg.jpg",
    desc: "Robinet mitigeur de baignoire et douche chromé fixation murale",
    price: 34.9,
  },
  {
    id: 9,
    name: "Papier de verre",
    utility: "baignoire",
    image: "https://i.imgur.com/3BQ75uz.jpg",
    desc: "Feuille abrasive grains 180",
    price: 4.9,
  },
  {
    id: 10,
    name: "Crayon de menuisier",
    utility: "baignoire-carrelage",
    image: "https://i.imgur.com/5m2sKST.jpg",
    desc: "Kit de 12 crayons de charpentier de 18cm",
    price: 5.6,
  },
  {
    id: 11,
    name: "Perceuse",
    utility: "baignoire",
    image: "https://i.imgur.com/b6fuD8q.jpg",
    desc: "Perceuse à percussion sans fil 18V 21000cps/min BLACK+DECKER BCD003BA10S-QW + 2 batteries 1.5Ah + 10 accessoires + chargeur 400mA",
    price: 99.7,
  },
  {
    id: 12,
    name: "Cutter",
    utility: "baignoire",
    image: "https://i.imgur.com/bxZUBIw.jpg",
    desc: "Cutter - 1 Lame 18 mm - Corps Métallique ",
    price: 4.5,
  },
  {
    id: 13,
    name: "Baignoire",
    utility: "baignoire",
    image: "https://i.imgur.com/LGQP9Nd.jpg",
    desc: "Baignoire 160 x 70 CORVETTE",
    price: 178.9,
  },
  {
    id: 14,
    name: "Pommeau de douche",
    utility: "baignoire",
    image: "https://i.imgur.com/mkn5n6R.jpg",
    desc: "Set de Douche Douchette 6 Jets Douche Kit Flexible de Douche 1,5M et Support de Douche Mural Chromé",
    price: 45.8,
  },
  {
    id: 15,
    name: "Rideau de douche",
    utility: "baignoire",
    image: "https://i.imgur.com/ofbGY53.jpg",
    desc: "Ensemble de rideaux de douche Tissu de salle de bain Rideaux d'automne imperméables colorés drôles avec la taille standard 72 par 72",
    price: 35.7,
  },
  {
    id: 16,
    name: "Cordeau à tracer ",
    utility: "carrelage",
    image: "https://i.imgur.com/TGP9kCP.jpg",
    desc: "Cordeau à tracer et craie bleue Magnusson",
    price: 7.9,
  },
  {
    id: 17,
    name: "Mortier",
    utility: "carrelage",
    image: "https://i.imgur.com/qYpj8JA.jpg",
    desc: "Mortier colle Gris 25kg",
    price: 6.5,
  },
  {
    id: 18,
    name: "Truelle",
    utility: "carrelage",
    image: "https://i.imgur.com/alAmCYL.jpg",
    desc: "Truelle ronde Performance Power 18 cm",
    price: 3.9,
  },
  {
    id: 19,
    name: "Spatule crantée",
    utility: "carrelage",
    image: "https://i.imgur.com/V0s6TBP.jpg",
    desc: "Spatule à colle pour sols",
    price: 3.6,
  },
  {
    id: 20,
    name: "Coupe carrelage",
    utility: "carrelage",
    image: "https://i.imgur.com/db5ibM8.jpg",
    desc: "Coupe carrelage manuel Magnusson MTC630 630 mm",
    price: 37.9,
  },
  {
    id: 21,
    name: "Croisillons",
    utility: "carrelage",
    image: "https://i.imgur.com/XnCjR5g.jpg",
    desc: "Lot de 250 croisillons",
    price: 2.4,
  },
  {
    id: 22,
    name: "Maillet",
    utility: "carrelage",
    image: "https://i.imgur.com/ec8Nee5.jpg",
    desc: "Maillet de carreleur en caoutchouc noir, 0,22 kg",
    price: 3.5,
  },
  {
    id: 23,
    name: "Ventouse",
    utility: "carrelage",
    image: "https://i.imgur.com/1oaXoOq.jpg",
    desc: "Double ventouse capacité 50kg",
    price: 13.8,
  },
  {
    id: 24,
    name: "Genouillère",
    utility: "carrelage",
    image: "https://i.imgur.com/sfMaSxR.jpg",
    desc: "Genouillères Result NOIR",
    price: 6.8,
  },
];

export default items;
